modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0-only"

[[mods]]
modId="aurora_core"
version="${version}"
displayName="Aurora Core"
description='''Infraestrutura compartilhada dos módulos oficiais Aurora.'''

[[dependencies.aurora_core]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.aurora_core]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="CLIENT"
