org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.20.1
fabric_minecraft_range=~1.20.1
forge_minecraft_range=[1.20.1,1.21)
forge_loader_range=[47,)
java_version=17
compile_java_version=17
enabled_platforms=fabric,forge
archives_base_name=aurora-companion-mod
mod_version=0.2.0
maven_group=com.aurora

architectury_version=9.2.14
fabric_loader_version=0.16.14
forge_version=1.20.1-47.4.23
