plugins { id "com.github.johnrengelman.shadow" }
architectury { platformSetupLoomIde(); fabric() }
configurations { common; shadowCommon; compileClasspath.extendsFrom common; runtimeClasspath.extendsFrom common }
dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }
    shadowCommon files(rootProject.file("../../api/build/libs/aurora-core-api-1.0.0.jar"))
    shadowCommon files(rootProject.file("../../runtime/build/libs/aurora-core-runtime-1.0.0.jar"))
    shadowCommon "com.google.code.gson:gson:2.10.1"
    shadowCommon "org.java-websocket:Java-WebSocket:1.5.6"
}
processResources {
    inputs.properties "version": project.version, "minecraft_range": rootProject.fabric_minecraft_range, "java_version": rootProject.java_version
    filesMatching("fabric.mod.json") { expand "version": project.version, "minecraft_range": rootProject.fabric_minecraft_range, "java_version": rootProject.java_version }
}
shadowJar {
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
    relocate "com.google.gson", "com.aurora.core.shadow.gson"
    relocate "org.java_websocket", "com.aurora.core.shadow.websocket"
    exclude "META-INF/versions/**", "module-info.class"
    manifest { attributes "MixinConfigs": "aurora_core.mixins.json" }
}
remapJar { input.set shadowJar.archiveFile; dependsOn shadowJar }
