pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.minecraftforge.net/" }
        gradlePluginPortal()
    }
}

rootProject.name = "aurora-core-minecraft-1.19.2"
include("common", "fabric", "forge")
